language: python
python: '3.6'
os: linux
cache: pip
install:
- pip install -r requirements-test.txt
- pip install .
script:
- DOCKER=1 pytest tests
deploy:
  provider: pypi
  user: __token__
  password:
    secure: sqQRsKQWr1fTo3mTuuIeJhgCAT+rtkE5q5GdU7avrox1UwzmfKcVjs4uzce6PbiB3BdothqCB6yAJ/PPIJyoiOxTsMfo6cqKP5um2xt79awTNJIwtB82PeEjxO/c4iJNtNaxAJUqIoBHAxT+w74Z4orC9UukSbHxDjQU6mxUu2W0z2f3ZRs47sCGuA+FX9cZceQhlyIrQ30v22xQpnbisa7AeUtPw57WvFNL07rXiTo65FVF8cYiZHc3ItRQ0iK3AHh3cstG67lOObISvd4y5r6FNGAB6bzoHsfRPxMf0bBEuSTdZ36PVN0dZWeVxBFXGSXqMMlESIWHXCOHisRLqTCXo/ZeRZhsFiqg7PDv9mn5rO9iGh4CygnC/Ltgr8r4Uj1eRNhfQJ5PPoMY2KhbfTqKeBTsbrRTCQBY0mIj1Jw28WYeOIJA3QnoJYBwpxVLNdWW3YBKA5qppYpO1/wzAKlP7/+4/QycDkvoOqbObb3wcONv5xq/D3CtD8tgsqnxVZvvdWN/r3fBmHnhhx2TAUpbCdPUCJOm2Q6yfWYqxOUBEeLwyXQzcoD0KSLFI2w0fMQLiBjSlRddFLGVq5rez/SLZb3FPpPn2DtBiyakmFn4wP3KZvoAegbCAXCGlhtcYEVjNVc5kwV80VXeBOsbYMvCAfEF1Acq5AnnEoRi83Y=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
