language: python
python: '3.6'
os: linux
cache: pip
install:
- pip install -r requirements-test.txt
- pip install .
script:
- DOCKER=1 pytest tests
deploy:
  provider: pypi
  user: atait
  password:
    secure: hYPAA6OMGjDkSqd23WVIAIXn29uKDN0PTjJcfTDclamlokGlxtc7L7VQG7OLgvO6c/W4KrYAVK6IvGj502De/vi8uqrrevyOUHT5AEgkm06mhh5ElfyXoVhVbTIJJjR2nmZKsa+RiLHbjyN+jVJFXiXyMQySaa3/QW7InRHDPiooGxvQ8EQMDdq4lTh0sjnKGC6ihaEoc+XRWsjotqswpJcr0Wk1+bQRwlkRwiNIykCfEgdpguGM+XLR5TyoLDj+iFnXJhyF8+e5DT98qLoSK+FqlNTJrvJ06JcO5IcQkP5tzOQTt+sq5+DTkfKaLrqZ803cx87fgWe//x5UlPAPyvBVaAKkf4PizsccWB+BLhU9d7mFsCA7sBUE1wEJBU8pO0otXjj8GhTVgawxHqg4b4/ip9KSrkTa1FNvo38jfkK3pGX/klEBrwK6jtGFWhkiYM4j8iYBTK/heb3gtHENuXfrIMX/VnJs9A5Ix6l4Qwf1E39Z3u8nH+MssHFGS0oK8qiSbgoZqdFhRna/6pUdMsIWrGUXtviQ8Cg80OYnaZexmO2z5WJ0Xes2aiSmaDQCv9jNgDNcG7wRLwup+Z8QTZ9BVXFkGKQzOyKl7dbfpW2KZdecQCaZm35eyOEfS9WVLk0AuJU8CyfDrec+D7waGAKR+W2pKahrHUPvTJp2Bng=
  distributions: sdist bdist_wheel
  on:
    tags: true
    branch: master
